### ISSUE TITLE
Bad label in menu Project in French version

### ISSUE THREAD

**Issue by fr-ad33** [liushuyu/lmms-translations#23]
LMMS Version 1.2.0-rc5 (win32/x86_64, Qt 5.4.2, GCC 4.9.4 20150716 (prerelease))

Hi all,
just a little mistake to report in French LMMS, menu Project.
Line below Ctrl+Alt+S (save as new version), "Sauvegarder en tant que omdèle par défaut"?

omdèle may be replaced by modèle.

**Comment by liushuyu** [comment]
Pinging @trebmuh

**Comment by trebmuh** [comment]
@fr-ad33 : I've already fixed this typo a while ago if I remember correctly. You may want to check with a newer version than this one. See https://github.com/LMMS/lmms/releases . If this typo is still present with 1.2.0-rc6, then we have an issue.

@liushuyu checking it quickly, it looks all good to me : https://github.com/liushuyu/lmms-translations/blob/master/lmms/fr.ts#L5148 you can probably close this issue.

**Comment by liushuyu** [comment]
Okay, mark as resolved

**Comment by trebmuh** [comment]
@liushuyu I think we might have a problem here. A said before, the typo is fixed in the translation : 
https://github.com/liushuyu/lmms-translations/blob/master/lmms/fr.ts#L4761 , but looking in the 1.2.0 version, it is not. Do you know if the translation has been merged before the 1.2.0 release?

Edit: it looks it hasn't been :/ https://github.com/LMMS/lmms/blob/stable-1.2/data/locale/fr.ts#L3968
